<?php
       $lang = array(
       "wellcome" => "Welcome to",
       "h3" => "INSTRUCTIONS", 
       "p" => "Anyone can play word of the day.<br>
              The objective is simple, to guess the hidden word. The word has 5 letters and you have 6 tries to guess it. The word is the same for all people on that day.<br>
              Each attempt must be a valid word. In each round the game paints each letter a color indicating whether or not that letter is in the word and if it is in the correct position.",
       "li_1" => "<span style='color:green'><b>GREEN</b></span> means that the letter R is in the word and in the position <span style='color:green'><b>CORRECT</b></span>.",
       "li_2" => "<span style='color:yellow'><b>YELLOW</b></span> means that the letter is present in the word but in the position <span style='color:yellow '><b>INCORRECT</b></span>.",
       "li_3" => "<span style='color:grey'><b>GREY</b></span> means that the letter <span style='color:grey'><b>NO</b></span> it's in the word",
       "h4" => "Enter a username:",
       "placeholder" => "Username",
       "home" => "Home",
       "bottonPlay" => "Play",
       "reset" => "Reset",
       "resetTitle" => "Reset Session",
       "resetP" => "Are you sure you want to reset the session data?",
       "resetCancel" => "Cancel",
       "resetConfirmation" => "Reset",
       "letra" => "Ñ",
       "borrar" => "Delete",
       "enviar" => "SEND",
       "ganar" => "YOU WIN!",
       "perder" => "YOU LOSE!",
       "puntos" => "POINTS: ",
       "exitoses" => "WINS: ",
       "errors" => "LOSES: ",
       "intents" => "ATTEMPTS: ",
       "es" => "Castellano",
       "en" => "English",
       "ca" => "Català",
       "file" => "english_5.txt",
       "publicar" => "Want to post your score? You will be returned to the start screen.",
       "yes" => "YES",
       "volverInicio" => "Return to home page?",
       "volverBoton" => "COME BACK"
);