<?php
    $lang = array(
            "wellcome" => "Bienvenido a",
            "h3" => "INSTRUCCIONES",
            "p" => "Cualquier persona puede jugar en la palabra del día.<br>
            El objetivo es simple, adivinar la palabra oculta. La palabra tiene 5 letras y tienes 6 intentos por adivinarla. La palabra es la misma para todas las personas en ese día.<br>
            Cada intento debe ser una palabra válida. En cada ronda el juego pinta cada letra de un color indicando si esa letra se encuentra o no en la palabra y si se encuentra en la posición correcta.",
            "li_1" => "<span style='color:green'><b>VERDE</b></span> significa que la letra R está en la palabra y en la posición <span style='color:green'><b>CORRECTA</b></span>.",
            "li_2" => "<span style='color:yellow'><b>AMARILLO</b></span> significa que la letra está presente en la palabra pero en la posición <span style='color:yellow'><b>INCORRECTA</b></span>.",
            "li_3" => "<span style='color:grey'><b>GRIS</b></span> significa que la letra <span style='color:grey'><b>NO</b></span> está en la palabra.",
            "h4" => "Introduce un nombre de usuario:",
            "placeholder" => "Nombre de usuario",
            "home" => "Inicio",
            "bottonPlay" => "Jugar",
            "reset" => "Reiniciar",
            "resetTitle" => "Reiniciar Sesión",
            "resetP" => "¿Está seguro de que quiere reiniciar los datos de la sesión?",
            "resetCancel" => "Cancelar",
            "resetConfirmation" => "Reiniciar",
            "letra" => "Ñ",
            "borrar" => "Borrar",
            "enviar" => "Enviar",
            "ganar" => "HAS GANADO!",
            "perder" => "HAS PERDIDO!",
            "puntos" => "PUNTOS: ",
            "exitoses" => "VICTORIAS: ",
            "errors" => "DERROTAS: ",
            "intents" => "INTENTOS: ",
            "es" => "Castellano",
            "en" => "English",
            "ca" => "Català",
            "file" => "castellano_5.txt",
            "publicar" => "¿Quieres publicar tu puntuación? Volverás a la pantalla de incio.",
            "yes" => "SÍ",
            "volverInicio" => "¿Quieres volver a la página de inicio?",
            "volverBoton" => "VOLVER"
    );